console.log('hello, world');
var x = document.querySelector('h1');
console.log(x);
console.dir(x);
var y = document.querySelector('#explanation');
console.log(y);
console.dir(y);
var z = document.querySelector('.hint');
console.log(z);
console.dir(z);
var a = document.querySelectorAll('p');
console.log(a);
var b = document.querySelectorAll('.example-link');
console.log(b);
